### ISSUE TITLE
Обсуждение документации (рпз)

### ISSUE THREAD

**Issue by xreyaf** [xreyaf/cinema-app#4]
Как всегда не по плану, однако что есть, то [есть](https://github.com/xreyaf/cinema-app/blob/master/doc/%D0%A0%D0%B0%D1%81%D1%87%D0%B5%D1%82%D0%BD%D0%BE-%D0%BF%D0%BE%D1%8F%D1%81%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%BA%D0%B0.docx). Прошу любить и жаловать :)

**Вопросы:** 

- куда придумать концептуальную модель и нужна ли вообще?

- каких пунктов в исследовательской части не хватает?

**Comment by TheKekMan** [comment]
Работай!
